name: Weekly System Health Report

on:
  schedule:
    # Runs every Monday at 9 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * 1'
  # Also allow manual triggering
  workflow_dispatch:

jobs:
  monitoring:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd monitoring
        pip install -r requirements.txt
        
    - name: Run monitoring script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        REPORT_EMAIL: ${{ secrets.REPORT_EMAIL }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: |
        cd monitoring
        python monitor.py